### PR TITLE
Google Drive Uploader Bot

### PR DESCRIPTION
**Pull request by VishalS-HK**
Hello.

This is the implementation of file uploader to GDrive using PyDrive2.

Please provide your feedback/changes on this.
Thank You

### CODE REVIEW

**Comment by anupammaurya6767** [comment]
@VishalS-HK can you also add for folder as well

**Comment by VishalS-HK** [comment]
Will do. Can I get a few days to finish it? If you don't mind.

**Comment by anupammaurya6767** [comment]
yeah sure also every time we upload a file we have to authenticate?

**Comment by VishalS-HK** [comment]
Authentication is only done once.

**Comment by anupammaurya6767** [comment]
@VishalS-HK use token file instead

**Comment by VishalS-HK** [comment]
@anupammaurya6767 not every time, when you setup the Google API and run the code for the first time, it will ask for it.

**Comment by VishalS-HK** [comment]
> @VishalS-HK use token file instead

Could you elaborate on this?

**Comment by anupammaurya6767** [comment]
> > @VishalS-HK use token file instead
> 
> Could you elaborate on this?

we need to run this script on the server then authentication is an issue so use the token file for authentication purposes

**Pull request merged**
